### ISSUE TITLE
Size plots

### ISSUE THREAD

**Issue by smith6jt-cop** [ColemanRHarris/mxnorm#11]
Request ability to size plots when analyzing multiple markers.
![test_density](https://github.com/ColemanRHarris/mxnorm/assets/73438963/936c1198-507b-4e21-8b1f-110a40a2535b)

**Comment by ColemanRHarris** [comment]
Hi @smith6jt-cop, this is likely an issue with your window size and is not an `mxnorm` issue. Note that plot objects created using `mxnorm` are `ggplot2` objects and can be adjusted as such. Here are some suggested options:

- https://stackoverflow.com/questions/38833042/r-making-bigger-graphs-when-using-facet-wrap
- https://ggplot2.tidyverse.org/reference/facet_grid.html
