### ISSUE TITLE
automated testing

### ISSUE THREAD

**Issue by tijeco** [ColemanRHarris/mxnorm#5]
It seems that you have a set of test scripts, but I don't see where them being implemented in some sort of continuous integration framework. You can set up a reasonably simple github actions pipeline to run those tests each time you make a commit. It's a good habit to get into, because it can provide immediate input about potential bugs that you have introduced that may cause a simple test to fail.

**Comment by ColemanRHarris** [comment]
Automated testing for both the `R CMD check` and code coverage has been added via the Github Actions pipeline in the commit here: 62e9b45756dd3bce559ce8d73307e0f2242cd6c9
