### ISSUE TITLE
Interesting issue when running in conda environment

### ISSUE THREAD

**Issue by tijeco** [ColemanRHarris/mxnorm#6]
As mentione in #4, I've installed mxnorm on a fresh computer in a conda environment.

I was going through the examples in the README and ran into this when I executed the follwowing:

```R
mx_otsu = run_otsu_discordance(mx_norm,
                        table="both",
                        threshold_override = NULL,
                        plot_out = FALSE)
```

The output was:

```
No non-system installation of Python could be found.
Would you like to download and install Miniconda?
Miniconda is an open source environment management system for Python.
See https://docs.conda.io/en/latest/miniconda.html for more details.

Would you like to install Miniconda? [Y/n]
```

For context, outside of conda, I don't have python installed (there is no /usr/bin/python).

In the conda environment that I am using and have mxnorm installed in, python is installed, and should be accessible through the $PATH.

Also, I already have miniconda installed, so I certainly wouldn't want to proceed with installing it again.

I think some of this should be mentioned in the documentation, as far as dependencies go.

Also, is there a way to determine that miniconda is installed, or that mxnorm is already installed in a conda environment?

**Comment by ColemanRHarris** [comment]
As discussed in https://github.com/ColemanRHarris/mxnorm/issues/4, I was able to setup a similar Docker container and re-create this issue. Based on some digging in the `conda` repository, this was a known issue (https://github.com/rstudio/reticulate/issues/607) and was seemingly addressed. The steps I took to work around it were:
- Did not install Miniconda via the R console.
- Used `reticulate::py_config()` to setup my desired Python environment.
- Ensured `scikit-image` was installed in the same location as the Python environment.

These steps allowed me to run the command you listed above without error, and have been recreated in the [Dependencies](https://github.com/ColemanRHarris/mxnorm#dependencies) section of the README.
