### ISSUE TITLE
NaN produced from mean_divide transform

### ISSUE THREAD

**Issue by ansonkn** [ColemanRHarris/mxnorm#8]
Hi, I am getting an error when applying mx_normalize to the dat. Dat contains multi-channel fluorescent values and 3 slides. One of the channel in the last slides have all zero values and therefore a mean of 0. Was wondering if you can amend the code such that transformation of all zeros will result in all zeros instead of NaN in R. Thanks

`mx_normalize(mx_data = dat,
                       transform = "mean_divide",
                       method='None')`

**Comment by ColemanRHarris** [comment]
Hi @ansonkn, thank you for your comments! This issue should be fixed in the latest commits / release. Please let me know if you run into any other issues. Appreciate you using mxnorm!
